// <auto-generated />
namespace HiQo.StaffManagement.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Implement_UserEntity_changes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Implement_UserEntity_changes));
        
        string IMigrationMetadata.Id
        {
            get { return "201808281143028_Implement_UserEntity_changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
