// <auto-generated />
namespace HiQo.StaffManagement.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_ExceptionLog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_ExceptionLog));
        
        string IMigrationMetadata.Id
        {
            get { return "201809210935255_Create_ExceptionLog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
